### ISSUE TITLE
Algorithm Acknowledgement

### ISSUE THREAD

**Issue by SmartArtsStudio** [Pomax/svg-to-something#1]
That is quite the clever solution you have there. Did you come up with it all by yourself? I put quite a bit of effort into publishing the same solution you have, just a few months prior to your own. Under MIT license allowing anyone to do what they want with it. Refactoring "substantial portions" is included subject to the following conditions: 

"Copyright(c)  2016  Daniel Kristensen (www.smartArtsStudio.com.au)"
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

...if you don't agree the engine of smart-svg-path makes up a substantial portion of svg-path-reverse

One of the following lines...
"Inspired by smart-svg-path from Daniel Kristensen (www.smartArtsStudio.com.au)"
"Inspired by the work of Daniel Kristensen (www.smartArtsStudio.com.au)"

Might be appropriate to include instead, and much appreciated. Thanks.

**Comment by Pomax** [comment]
No, it isn't. This is how you reverse a path, as established and taught in thousands of programming courses across the planet since before I was born.

I've written font outline/path parsers [since 2010](https://github.com/pomax/php-font-parser), have worked on [general purpose graphics libraries since 2012](https://github.com/processing-js/processing-js) and authored a detailed primer on [the use of Bezier curves in pathed design](https://pomax.github.io/bezierinfo) that's been online since 2011, so even in 2016 I would have had no reason to look at anyone else's code, or publications. Writing a path parser is an almost trivial activity (it's just a DFA that you implement against the spec), and reversing a path not much more so (it's a DFA reversal with operator shifting).

**Comment by SmartArtsStudio** [comment]
Yes I am very familiar with your work. Before I had to find my own solution to this I scoured the internet including through both your Primer on Bézier Curves and Processing.js trying to see if either could already do it, or could at least shed some light on what would be required to reverse and SVG path. They didn't at the time. I wish they did at least 6 months before you published svg-path-reverse it would have saved me three months of spare time.

Surprisingly though Primer on Bézier Curves and Processing.js still don't contain either an article or an API on how to reverse an SVG path. 

Thanks for the Computer Science language for what we are doing. I googled a little: how to reverse svg path using those terms as well to see what I had been missing, but still no results.

You must be using Bing. All those thousands of courses apparently teaching this across the planet seemed to have achieved something the Music, Movie and Gaming industry with all their money combined haven’t been able to achieve, and that is how to keep their material almost impossible to find with Google.

This aside. I do think your Primer on Bézier Curves is awesome thanks for sharing your work. I'll be sure to  credit you for it if I ever refactor any substantial portions of it.

**Comment by Pomax** [comment]
Google or bing are unfortunately rather poor tools when it comes to finding good algorithm implementations, or pages that talk about them. Google Scholar may sometimes find you decent results, but the real sources of information I've found so far are simply asking questions on the more traditional graphics forums. The answers usually take a little longer to get, but they're also usually worth the wait.

Should you be puzzled or stuck with an algorithmic problem in the future, while no longer quite as well-know, the comp.graphics.algorithms newsgroup (which apparently has a google group now backing it, too, on https://groups.google.com/forum/#!forum/comp.graphics.algorithms) is an incredibly valuable resource as well when it comes to solving what to you may seem a difficult problem, but what others have already solved, sometimes surprisingly early on in the history of computer science (path reversal based on opcode and operands, for instance, has been around since at least the inception of postscript in 1982, and even metapost, in 1979, by Knuth, for which the source code can be found in various TeX distributions). I'm fairly certain that a good number of the "old guard" (e.g. authors whose names you might find on "Graphics Gems" articles) still check in on it from time to time, and I've had many great answers to problems I've had in the past there.

Stackoverflow is of course a more usual place these days, but in addition to those options, asking on an open source project that already solved the problem you're working (in this particular case, the inkscape developer list springs to mind, or even a project like paper.js, which also solved this problem quite a while ago) is usually met with devs being quite willing to help solve problems of an algorithmic nature, when asked.
